apiVersion: v1
kind: Service
metadata:
  name: comments-api-svc
  labels:
    app: comments-api
spec:
  type: LoadBalancer
  selector:
    app: comments-api
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
